/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.design;

import javax.swing.JPanel;

/**
 *
 * @author SayefReyadh
 */
public class LaboratorianFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LaboratorianFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        laboratorianPanel = new javax.swing.JPanel();
        reportDoctorIdLabel = new javax.swing.JLabel();
        reportDoctorIdTextField = new javax.swing.JTextField();
        reportSubjectTextField = new javax.swing.JTextField();
        reportSubjectLabel = new javax.swing.JLabel();
        reportDetailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportDetailsTextArea = new javax.swing.JTextArea();
        addReportButton = new javax.swing.JButton();
        reportPatientIdTextField = new javax.swing.JTextField();
        reportPatientIdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(200, 50, 1000, 700));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 20));
        setResizable(false);

        jToolBar1.setRollover(true);

        laboratorianPanel.setBackground(new java.awt.Color(0, 153, 153));

        reportDoctorIdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportDoctorIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportDoctorIdLabel.setText("Doctor Id");

        reportDoctorIdTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportDoctorIdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        reportSubjectTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportSubjectTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reportSubjectTextField.setText("Default All");

        reportSubjectLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportSubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportSubjectLabel.setText("Report Subject");

        reportDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportDetailsLabel.setText("Details");

        reportDetailsTextArea.setColumns(20);
        reportDetailsTextArea.setRows(5);
        jScrollPane1.setViewportView(reportDetailsTextArea);

        addReportButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addReportButton.setText("Add");

        reportPatientIdTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportPatientIdTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        reportPatientIdLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportPatientIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportPatientIdLabel.setText("Patient Id");

        javax.swing.GroupLayout laboratorianPanelLayout = new javax.swing.GroupLayout(laboratorianPanel);
        laboratorianPanel.setLayout(laboratorianPanelLayout);
        laboratorianPanelLayout.setHorizontalGroup(
            laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratorianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reportDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(reportPatientIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportDoctorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportSubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportDoctorIdTextField)
                    .addComponent(reportSubjectTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(reportPatientIdTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        laboratorianPanelLayout.setVerticalGroup(
            laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratorianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportPatientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportPatientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportDoctorIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportDoctorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportSubjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportSubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(laboratorianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laboratorianPanelLayout.createSequentialGroup()
                        .addComponent(reportDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(addReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(laboratorianPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaboratorianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaboratorianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaboratorianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaboratorianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaboratorianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReportButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel laboratorianPanel;
    private javax.swing.JLabel reportDetailsLabel;
    private javax.swing.JTextArea reportDetailsTextArea;
    private javax.swing.JLabel reportDoctorIdLabel;
    private javax.swing.JTextField reportDoctorIdTextField;
    private javax.swing.JLabel reportPatientIdLabel;
    private javax.swing.JTextField reportPatientIdTextField;
    private javax.swing.JLabel reportSubjectLabel;
    private javax.swing.JTextField reportSubjectTextField;
    // End of variables declaration//GEN-END:variables
}
