/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.design;

import database.NurseDatabase;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.NurseModel;
import model.PatientModel;

/**
 *
 * @author SayefReyadh
 */
public class NurseFrame extends javax.swing.JFrame {

    private NurseModel nurseModel;
    private NurseDatabase nurseDatabase;
    
    private static int nurseID;
    /**
     * Creates new form Login
     */
    public NurseFrame() {
        nurseID = 10234;
        
        nurseDatabase = new NurseDatabase();
        nurseModel = nurseDatabase.getNurseInformation(10234);
        nurseModel.setPatientList(nurseModel.getPatientList());
        nurseModel.setWardArrayString(nurseDatabase.getWardNameArrayList(10234));
       
        initComponents();
        
        loadWardNameComboBox();
    }

    public NurseFrame(int nurseId) {
        nurseID = nurseId;
        
        nurseDatabase = new NurseDatabase();
        nurseModel = nurseDatabase.getNurseInformation(nurseId);
        nurseModel.setPatientList(nurseModel.getPatientList());
        nurseModel.setWardArrayString(nurseDatabase.getWardNameArrayList(nurseId));
       
        
        initComponents();
        
        loadWardNameComboBox();
    }
    
    public void loadWardNameComboBox() {
        
        wardNameComboBox.removeAll();
        
        ArrayList<String> cols = nurseDatabase.getWardNameArrayList(nurseID);
        
        for (String col: cols) {
        wardNameComboBox.addItem(col);
        
        }
        
        
        loadTableData( (String) wardNameComboBox.getSelectedItem());
        
        wardNameComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
        loadTableData( (String) wardNameComboBox.getSelectedItem());
            }
        });
        
    }
    
    public void loadTableData(String wardName) {
        ArrayList<String> cols = new ArrayList<>();
        DefaultTableModel mTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        cols.add("Patient Name");
        cols.add("Patient Age");
        cols.add("Patient Address");
        
        for (String col : cols) {
           mTableModel.addColumn(col);
        }
        
        ArrayList<PatientModel> patients = nurseDatabase.getPatientList((String) wardNameComboBox.getSelectedItem());
        
        for (int i = 0 ; i < patients.size() ; i++) {
            PatientModel model = patients.get(i);
            String[] row = {model.getNameString(),model.getAgeString(), model.getAddressString()};
            
            mTableModel.addRow(row);
        }
        
        patientListTable.setModel(mTableModel);
        
        JTableHeader th = patientListTable.getTableHeader();
        th.setBackground(Color.GREEN);
        th.setFont( new Font( "Arial" , Font.BOLD, 13 ));

        patientListTable.removeAll(); // removing all previous data from table
        patientListTable.setModel(mTableModel); // adding new data list in the table

        patientListTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        patientListTable.setColumnSelectionAllowed(false);
        patientListTable.setRowSelectionAllowed(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nursePanel = new javax.swing.JPanel();
        wardNameLabel = new javax.swing.JLabel();
        wardNameComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientListTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(200, 50, 1000, 700));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 20));
        setResizable(false);

        nursePanel.setBackground(new java.awt.Color(0, 153, 153));

        wardNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wardNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wardNameLabel.setText("Ward Name");

        wardNameComboBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wardNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

        patientListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(patientListTable);

        javax.swing.GroupLayout nursePanelLayout = new javax.swing.GroupLayout(nursePanel);
        nursePanel.setLayout(nursePanelLayout);
        nursePanelLayout.setHorizontalGroup(
            nursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(nursePanelLayout.createSequentialGroup()
                .addComponent(wardNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wardNameComboBox, 0, 336, Short.MAX_VALUE))
        );
        nursePanelLayout.setVerticalGroup(
            nursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nursePanelLayout.createSequentialGroup()
                .addGroup(nursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wardNameComboBox)
                    .addComponent(wardNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NurseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NurseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NurseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NurseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel nursePanel;
    private javax.swing.JTable patientListTable;
    private javax.swing.JComboBox<String> wardNameComboBox;
    private javax.swing.JLabel wardNameLabel;
    // End of variables declaration//GEN-END:variables
}
